// Embedded Control UI HTML
// Generated from ui/index.html

#ifndef OPENCLAW_GATEWAY_CONTROL_UI_H
#define OPENCLAW_GATEWAY_CONTROL_UI_H

namespace openclaw {

const char* CONTROL_UI_HTML = 
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "    <meta charset=\"UTF-8\">\n"
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "    <title>OpenClaw Control</title>\n"
    "    <style>\n"
    "        :root {\n"
    "            --bg-primary: #1a1a1a;\n"
    "            --bg-secondary: #2d2d2d;\n"
    "            --bg-tertiary: #383838;\n"
    "            --text-primary: #e0e0e0;\n"
    "            --text-secondary: #a0a0a0;\n"
    "            --border: #404040;\n"
    "            --accent: #00a8ff;\n"
    "            --success: #00c851;\n"
    "            --error: #ff4444;\n"
    "            --msg-sent: #005a9e;\n"
    "            --msg-received: #2d2d2d;\n"
    "        }\n"
    "        \n"
    "        * {\n"
    "            margin: 0;\n"
    "            padding: 0;\n"
    "            box-sizing: border-box;\n"
    "        }\n"
    "        \n"
    "        body {\n"
    "            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
    "            background: var(--bg-primary);\n"
    "            color: var(--text-primary);\n"
    "            line-height: 1.6;\n"
    "            display: flex;\n"
    "            flex-direction: column;\n"
    "            height: 100vh;\n"
    "        }\n"
    "        \n"
    "        header {\n"
    "            background: var(--bg-secondary);\n"
    "            padding: 15px 20px;\n"
    "            border-bottom: 2px solid var(--border);\n"
    "            flex-shrink: 0;\n"
    "        }\n"
    "        \n"
    "        h1 {\n"
    "            font-size: 20px;\n"
    "            display: flex;\n"
    "            align-items: center;\n"
    "            gap: 10px;\n"
    "        }\n"
    "        \n"
    "        .status {\n"
    "            display: inline-block;\n"
    "            width: 10px;\n"
    "            height: 10px;\n"
    "            border-radius: 50%;\n"
    "            background: var(--error);\n"
    "        }\n"
    "        \n"
    "        .status.connected {\n"
    "            background: var(--success);\n"
    "            animation: pulse 2s infinite;\n"
    "        }\n"
    "        \n"
    "        @keyframes pulse {\n"
    "            0%, 100% { opacity: 1; }\n"
    "            50% { opacity: 0.5; }\n"
    "        }\n"
    "        \n"
    "        .main-container {\n"
    "            display: flex;\n"
    "            flex: 1;\n"
    "            overflow: hidden;\n"
    "        }\n"
    "        \n"
    "        .sidebar {\n"
    "            width: 300px;\n"
    "            background: var(--bg-secondary);\n"
    "            border-right: 1px solid var(--border);\n"
    "            display: flex;\n"
    "            flex-direction: column;\n"
    "            overflow-y: auto;\n"
    "        }\n"
    "        \n"
    "        .chat-container {\n"
    "            flex: 1;\n"
    "            display: flex;\n"
    "            flex-direction: column;\n"
    "            background: var(--bg-primary);\n"
    "        }\n"
    "        \n"
    "        .card {\n"
    "            background: var(--bg-secondary);\n"
    "            border-bottom: 1px solid var(--border);\n"
    "            padding: 15px;\n"
    "        }\n"
    "        \n"
    "        .card h2 {\n"
    "            font-size: 16px;\n"
    "            margin-bottom: 12px;\n"
    "            color: var(--accent);\n"
    "        }\n"
    "        \n"
    "        .stat {\n"
    "            display: flex;\n"
    "            justify-content: space-between;\n"
    "            padding: 6px 0;\n"
    "            font-size: 13px;\n"
    "        }\n"
    "        \n"
    "        .stat-label {\n"
    "            color: var(--text-secondary);\n"
    "        }\n"
    "        \n"
    "        .stat-value {\n"
    "            font-weight: 600;\n"
    "        }\n"
    "        \n"
    "        .chat-header {\n"
    "            background: var(--bg-secondary);\n"
    "            padding: 15px 20px;\n"
    "            border-bottom: 1px solid var(--border);\n"
    "            flex-shrink: 0;\n"
    "        }\n"
    "        \n"
    "        .chat-title {\n"
    "            font-size: 16px;\n"
    "            font-weight: 600;\n"
    "        }\n"
    "        \n"
    "        .chat-subtitle {\n"
    "            font-size: 12px;\n"
    "            color: var(--text-secondary);\n"
    "            margin-top: 2px;\n"
    "        }\n"
    "        \n"
    "        .messages {\n"
    "            flex: 1;\n"
    "            overflow-y: auto;\n"
    "            padding: 20px;\n"
    "            display: flex;\n"
    "            flex-direction: column;\n"
    "            gap: 12px;\n"
    "        }\n"
    "        \n"
    "        .message {\n"
    "            max-width: 70%;\n"
    "            padding: 10px 14px;\n"
    "            border-radius: 12px;\n"
    "            font-size: 14px;\n"
    "            line-height: 1.4;\n"
    "            word-wrap: break-word;\n"
    "        }\n"
    "        \n"
    "        .message.sent {\n"
    "            align-self: flex-end;\n"
    "            background: var(--msg-sent);\n"
    "            border-bottom-right-radius: 4px;\n"
    "        }\n"
    "        \n"
    "        .message.received {\n"
    "            align-self: flex-start;\n"
    "            background: var(--msg-received);\n"
    "            border-bottom-left-radius: 4px;\n"
    "            border: 1px solid var(--border);\n"
    "        }\n"
    "        \n"
    "        .message-meta {\n"
    "            font-size: 11px;\n"
    "            color: var(--text-secondary);\n"
    "            margin-top: 4px;\n"
    "            display: flex;\n"
    "            justify-content: space-between;\n"
    "            align-items: center;\n"
    "        }\n"
    "        \n"
    "        .message-sender {\n"
    "            font-weight: 600;\n"
    "            color: var(--accent);\n"
    "        }\n"
    "        \n"
    "        .message-time {\n"
    "            opacity: 0.7;\n"
    "        }\n"
    "        \n"
    "        .chat-input-container {\n"
    "            background: var(--bg-secondary);\n"
    "            border-top: 1px solid var(--border);\n"
    "            padding: 15px 20px;\n"
    "            flex-shrink: 0;\n"
    "        }\n"
    "        \n"
    "        .chat-controls {\n"
    "            display: flex;\n"
    "            gap: 10px;\n"
    "            margin-bottom: 10px;\n"
    "        }\n"
    "        \n"
    "        .input-group {\n"
    "            flex: 1;\n"
    "            display: flex;\n"
    "            flex-direction: column;\n"
    "            gap: 5px;\n"
    "        }\n"
    "        \n"
    "        .input-group label {\n"
    "            font-size: 11px;\n"
    "            color: var(--text-secondary);\n"
    "            text-transform: uppercase;\n"
    "            font-weight: 600;\n"
    "        }\n"
    "        \n"
    "        .input-group select,\n"
    "        .input-group input[type=\"text\"] {\n"
    "            background: var(--bg-tertiary);\n"
    "            border: 1px solid var(--border);\n"
    "            color: var(--text-primary);\n"
    "            padding: 8px 10px;\n"
    "            border-radius: 6px;\n"
    "            font-size: 13px;\n"
    "            font-family: inherit;\n"
    "        }\n"
    "        \n"
    "        .input-group select:focus,\n"
    "        .input-group input[type=\"text\"]:focus {\n"
    "            outline: none;\n"
    "            border-color: var(--accent);\n"
    "        }\n"
    "        \n"
    "        .message-input-row {\n"
    "            display: flex;\n"
    "            gap: 10px;\n"
    "        }\n"
    "        \n"
    "        #messageInput {\n"
    "            flex: 1;\n"
    "            background: var(--bg-tertiary);\n"
    "            border: 1px solid var(--border);\n"
    "            color: var(--text-primary);\n"
    "            padding: 10px 14px;\n"
    "            border-radius: 20px;\n"
    "            font-size: 14px;\n"
    "            font-family: inherit;\n"
    "            resize: none;\n"
    "        }\n"
    "        \n"
    "        #messageInput:focus {\n"
    "            outline: none;\n"
    "            border-color: var(--accent);\n"
    "        }\n"
    "        \n"
    "        #sendBtn {\n"
    "            background: var(--accent);\n"
    "            color: white;\n"
    "            border: none;\n"
    "            padding: 10px 24px;\n"
    "            border-radius: 20px;\n"
    "            font-size: 14px;\n"
    "            font-weight: 600;\n"
    "            cursor: pointer;\n"
    "            transition: background 0.2s;\n"
    "        }\n"
    "        \n"
    "        #sendBtn:hover {\n"
    "            background: #0095e8;\n"
    "        }\n"
    "        \n"
    "        #sendBtn:disabled {\n"
    "            background: var(--border);\n"
    "            cursor: not-allowed;\n"
    "        }\n"
    "        \n"
    "        .empty-state {\n"
    "            flex: 1;\n"
    "            display: flex;\n"
    "            flex-direction: column;\n"
    "            align-items: center;\n"
    "            justify-content: center;\n"
    "            color: var(--text-secondary);\n"
    "            padding: 40px;\n"
    "            text-align: center;\n"
    "        }\n"
    "        \n"
    "        .empty-state-icon {\n"
    "            font-size: 48px;\n"
    "            margin-bottom: 16px;\n"
    "            opacity: 0.3;\n"
    "        }\n"
    "        \n"
    "        .log-entry {\n"
    "            font-family: 'Courier New', monospace;\n"
    "            font-size: 11px;\n"
    "            padding: 3px 0;\n"
    "            color: var(--text-secondary);\n"
    "        }\n"
    "        \n"
    "        .log-entry.error { color: var(--error); }\n"
    "        .log-entry.warn { color: #ffa502; }\n"
    "        .log-entry.info { color: var(--text-primary); }\n"
    "        \n"
    "        #logs {\n"
    "            max-height: 150px;\n"
    "            overflow-y: auto;\n"
    "            font-size: 11px;\n"
    "        }\n"
    "    </style>\n"
    "</head>\n"
    "<body>\n"
    "    <header>\n"
    "        <h1>\n"
    "            <span class=\"status\" id=\"status\"></span>\n"
    "            OpenClaw Gateway\n"
    "        </h1>\n"
    "    </header>\n"
    "    \n"
    "    <div class=\"main-container\">\n"
    "        <div class=\"sidebar\">\n"
    "            <div class=\"card\">\n"
    "                <h2>Status</h2>\n"
    "                <div class=\"stat\">\n"
    "                    <span class=\"stat-label\">Connection</span>\n"
    "                    <span class=\"stat-value\" id=\"conn-status\">Disconnected</span>\n"
    "                </div>\n"
    "                <div class=\"stat\">\n"
    "                    <span class=\"stat-label\">Protocol</span>\n"
    "                    <span class=\"stat-value\" id=\"protocol\">-</span>\n"
    "                </div>\n"
    "                <div class=\"stat\">\n"
    "                    <span class=\"stat-label\">Server</span>\n"
    "                    <span class=\"stat-value\" id=\"version\">-</span>\n"
    "                </div>\n"
    "            </div>\n"
    "            \n"
    "            <div class=\"card\">\n"
    "                <h2>Health</h2>\n"
    "                <div class=\"stat\">\n"
    "                    <span class=\"stat-label\">Clients</span>\n"
    "                    <span class=\"stat-value\" id=\"clients\">0</span>\n"
    "                </div>\n"
    "                <div class=\"stat\">\n"
    "                    <span class=\"stat-label\">Port</span>\n"
    "                    <span class=\"stat-value\" id=\"port\">-</span>\n"
    "                </div>\n"
    "            </div>\n"
    "            \n"
    "            <div class=\"card\">\n"
    "                <h2>Activity Log</h2>\n"
    "                <div id=\"logs\"></div>\n"
    "            </div>\n"
    "        </div>\n"
    "        \n"
    "        <div class=\"chat-container\">\n"
    "            <div class=\"chat-header\">\n"
    "                <div class=\"chat-title\">Chat Interface</div>\n"
    "                <div class=\"chat-subtitle\">Full-duplex communication with all registered plugins</div>\n"
    "            </div>\n"
    "            \n"
    "            <div class=\"messages\" id=\"messages\">\n"
    "                <div class=\"empty-state\">\n"
    "                    <div class=\"empty-state-icon\">💬</div>\n"
    "                    <p>No messages yet</p>\n"
    "                    <p style=\"font-size: 12px; margin-top: 8px;\">Send a message to start chatting</p>\n"
    "                </div>\n"
    "            </div>\n"
    "            \n"
    "            <div class=\"chat-input-container\">\n"
    "                <div class=\"chat-controls\">\n"
    "                    <div class=\"input-group\">\n"
    "                        <label>Channel</label>\n"
    "                        <select id=\"channelSelect\">\n"
    "                            <option value=\"telegram\">Telegram</option>\n"
    "                            <option value=\"whatsapp\">WhatsApp</option>\n"
    "                        </select>\n"
    "                    </div>\n"
    "                    <div class=\"input-group\">\n"
    "                        <label>Recipient</label>\n"
    "                        <input type=\"text\" id=\"recipientInput\" placeholder=\"Chat ID or username\">\n"
    "                    </div>\n"
    "                </div>\n"
    "                <div class=\"message-input-row\">\n"
    "                    <input type=\"text\" id=\"messageInput\" placeholder=\"Type a message...\" autocomplete=\"off\">\n"
    "                    <button id=\"sendBtn\" disabled>Send</button>\n"
    "                </div>\n"
    "            </div>\n"
    "        </div>\n"
    "    </div>\n"
    "    \n"
    "    <script>\n"
    "        let ws = null;\n"
    "        let connected = false;\n"
    "        let messageIdCounter = 1;\n"
    "        \n"
    "        const statusEl = document.getElementById('status');\n"
    "        const connStatusEl = document.getElementById('conn-status');\n"
    "        const protocolEl = document.getElementById('protocol');\n"
    "        const versionEl = document.getElementById('version');\n"
    "        const clientsEl = document.getElementById('clients');\n"
    "        const portEl = document.getElementById('port');\n"
    "        const logsEl = document.getElementById('logs');\n"
    "        const messagesEl = document.getElementById('messages');\n"
    "        const messageInput = document.getElementById('messageInput');\n"
    "        const sendBtn = document.getElementById('sendBtn');\n"
    "        const channelSelect = document.getElementById('channelSelect');\n"
    "        const recipientInput = document.getElementById('recipientInput');\n"
    "        \n"
    "        function log(message, level = 'info') {\n"
    "            const entry = document.createElement('div');\n"
    "            entry.className = `log-entry ${level}`;\n"
    "            const timestamp = new Date().toLocaleTimeString();\n"
    "            entry.textContent = `[${timestamp}] ${message}`;\n"
    "            logsEl.appendChild(entry);\n"
    "            logsEl.scrollTop = logsEl.scrollHeight;\n"
    "            \n"
    "            // Limit log entries to 50\n"
    "            while (logsEl.children.length > 50) {\n"
    "                logsEl.removeChild(logsEl.firstChild);\n"
    "            }\n"
    "        }\n"
    "        \n"
    "        function addMessage(msg, type = 'received') {\n"
    "            // Remove empty state if present\n"
    "            const emptyState = messagesEl.querySelector('.empty-state');\n"
    "            if (emptyState) {\n"
    "                emptyState.remove();\n"
    "            }\n"
    "            \n"
    "            const messageEl = document.createElement('div');\n"
    "            messageEl.className = `message ${type}`;\n"
    "            \n"
    "            const textEl = document.createElement('div');\n"
    "            textEl.textContent = msg.text;\n"
    "            messageEl.appendChild(textEl);\n"
    "            \n"
    "            const metaEl = document.createElement('div');\n"
    "            metaEl.className = 'message-meta';\n"
    "            \n"
    "            const time = new Date(msg.timestamp * 1000).toLocaleTimeString();\n"
    "            \n"
    "            if (type === 'received') {\n"
    "                const senderEl = document.createElement('span');\n"
    "                senderEl.className = 'message-sender';\n"
    "                senderEl.textContent = msg.from_name || msg.from;\n"
    "                metaEl.appendChild(senderEl);\n"
    "            }\n"
    "            \n"
    "            const timeEl = document.createElement('span');\n"
    "            timeEl.className = 'message-time';\n"
    "            timeEl.textContent = time;\n"
    "            metaEl.appendChild(timeEl);\n"
    "            \n"
    "            messageEl.appendChild(metaEl);\n"
    "            messagesEl.appendChild(messageEl);\n"
    "            messagesEl.scrollTop = messagesEl.scrollHeight;\n"
    "        }\n"
    "        \n"
    "        function connect() {\n"
    "            const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
    "            const wsUrl = `${protocol}//${window.location.hostname}:${window.location.port || 18789}/ws`;\n"
    "            \n"
    "            log(`Connecting to ${wsUrl}...`);\n"
    "            ws = new WebSocket(wsUrl);\n"
    "            \n"
    "            ws.onopen = () => {\n"
    "                log('Connected', 'info');\n"
    "                sendHello();\n"
    "            };\n"
    "            \n"
    "            ws.onmessage = (event) => {\n"
    "                try {\n"
    "                    const msg = JSON.parse(event.data);\n"
    "                    handleMessage(msg);\n"
    "                } catch (e) {\n"
    "                    log('Parse error: ' + e.message, 'error');\n"
    "                }\n"
    "            };\n"
    "            \n"
    "            ws.onerror = (error) => {\n"
    "                log('WebSocket error', 'error');\n"
    "            };\n"
    "            \n"
    "            ws.onclose = () => {\n"
    "                connected = false;\n"
    "                statusEl.classList.remove('connected');\n"
    "                connStatusEl.textContent = 'Disconnected';\n"
    "                sendBtn.disabled = true;\n"
    "                log('Disconnected', 'warn');\n"
    "                \n"
    "                setTimeout(connect, 5000);\n"
    "            };\n"
    "        }\n"
    "        \n"
    "        function sendHello() {\n"
    "            const hello = {\n"
    "                type: 'hello',\n"
    "                params: {\n"
    "                    minProtocol: 1,\n"
    "                    maxProtocol: 1,\n"
    "                    client: {\n"
    "                        id: 'gateway-ui-' + Date.now(),\n"
    "                        version: '1.0.0',\n"
    "                        platform: 'web',\n"
    "                        mode: 'chat'\n"
    "                    }\n"
    "                }\n"
    "            };\n"
    "            ws.send(JSON.stringify(hello));\n"
    "        }\n"
    "        \n"
    "        function handleMessage(msg) {\n"
    "            if (msg.type === 'hello-ok') {\n"
    "                connected = true;\n"
    "                statusEl.classList.add('connected');\n"
    "                connStatusEl.textContent = 'Connected';\n"
    "                protocolEl.textContent = `v${msg.protocol}`;\n"
    "                versionEl.textContent = msg.server.version || 'Unknown';\n"
    "                sendBtn.disabled = false;\n"
    "                log('Handshake complete', 'info');\n"
    "                \n"
    "                callMethod('health.get', {});\n"
    "            } else if (msg.type === 'result') {\n"
    "                handleResult(msg);\n"
    "            } else if (msg.type === 'event') {\n"
    "                handleEvent(msg);\n"
    "            } else if (msg.type === 'error') {\n"
    "                log(`Error: ${msg.error.message}`, 'error');\n"
    "            }\n"
    "        }\n"
    "        \n"
    "        function handleResult(msg) {\n"
    "            const result = msg.result;\n"
    "            \n"
    "            if (result.clients !== undefined) {\n"
    "                clientsEl.textContent = result.clients;\n"
    "            }\n"
    "            if (result.port) {\n"
    "                portEl.textContent = result.port;\n"
    "            }\n"
    "            if (result.success !== undefined) {\n"
    "                if (result.success) {\n"
    "                    log('Message sent: ' + result.message_id, 'info');\n"
    "                } else {\n"
    "                    log('Send failed: ' + result.error, 'error');\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        \n"
    "        function handleEvent(msg) {\n"
    "            if (msg.event === 'chat.message') {\n"
    "                // Incoming message from a channel\n"
    "                const chatMsg = msg.payload;\n"
    "                log(`Message from ${chatMsg.from_name} on ${chatMsg.channel}`, 'info');\n"
    "                addMessage(chatMsg, 'received');\n"
    "            } else {\n"
    "                log(`Event: ${msg.event}`, 'info');\n"
    "            }\n"
    "        }\n"
    "        \n"
    "        let callId = 1;\n"
    "        function callMethod(method, params) {\n"
    "            const msg = {\n"
    "                type: 'call',\n"
    "                method: method,\n"
    "                params: params,\n"
    "                id: `req-${callId++}`\n"
    "            };\n"
    "            ws.send(JSON.stringify(msg));\n"
    "        }\n"
    "        \n"
    "        function sendMessage() {\n"
    "            const text = messageInput.value.trim();\n"
    "            const channel = channelSelect.value;\n"
    "            const recipient = recipientInput.value.trim();\n"
    "            \n"
    "            if (!text || !recipient) {\n"
    "                log('Please enter message and recipient', 'warn');\n"
    "                return;\n"
    "            }\n"
    "            \n"
    "            if (!connected) {\n"
    "                log('Not connected', 'error');\n"
    "                return;\n"
    "            }\n"
    "            \n"
    "            // Add to UI immediately as sent message\n"
    "            addMessage({\n"
    "                text: text,\n"
    "                timestamp: Math.floor(Date.now() / 1000),\n"
    "                from_name: 'You'\n"
    "            }, 'sent');\n"
    "            \n"
    "            // Send via gateway\n"
    "            callMethod('chat.send', {\n"
    "                channel: channel,\n"
    "                to: recipient,\n"
    "                text: text\n"
    "            });\n"
    "            \n"
    "            // Clear input\n"
    "            messageInput.value = '';\n"
    "            messageInput.focus();\n"
    "        }\n"
    "        \n"
    "        // Event listeners\n"
    "        sendBtn.addEventListener('click', sendMessage);\n"
    "        messageInput.addEventListener('keypress', (e) => {\n"
    "            if (e.key === 'Enter') {\n"
    "                sendMessage();\n"
    "            }\n"
    "        });\n"
    "        \n"
    "        // Connect on load\n"
    "        log('Initializing...', 'info');\n"
    "        connect();\n"
    "        \n"
    "        // Refresh health every 10 seconds\n"
    "        setInterval(() => {\n"
    "            if (connected) {\n"
    "                callMethod('health.get', {});\n"
    "            }\n"
    "        }, 10000);\n"
    "    </script>\n"
    "</body>\n"
    "</html>\n"
    "";

} // namespace openclaw

#endif // OPENCLAW_GATEWAY_CONTROL_UI_H
